package cmd

import (
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/gdamore/tcell/v2"
	"github.com/rivo/tview"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var forceOverwrite bool

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate deploy.yaml via interactive TUI",
	RunE: func(cmd *cobra.Command, args []string) error {
		const filename = "deploy.yaml"

		if _, err := os.Stat(filename); err == nil && !forceOverwrite {
			return fmt.Errorf("%s already exists (use --force to overwrite)", filename)
		}

		cfg := runInitTUI()
		if cfg == nil {
			fmt.Println("Cancelled.")
			return nil
		}

		data, err := yaml.Marshal(cfg)
		if err != nil {
			return fmt.Errorf("failed to marshal config: %w", err)
		}

		header := "# go-deploy configuration\n# Generated by gondola init\n\n"
		if err := os.WriteFile(filename, []byte(header+string(data)), 0644); err != nil {
			return fmt.Errorf("failed to write %s: %w", filename, err)
		}

		fmt.Printf("Created %s\n", filename)
		return nil
	},
}

func runInitTUI() *Config {
	app := tview.NewApplication()

	cfg := &Config{
		Project: ProjectConfig{Name: "myapp"},
		Build: BuildConfig{
			Entry:    ".",
			Output:   "bin/myapp",
			GOOS:     "linux",
			GOARCH:   "amd64",
			LDFlags:  "-s -w",
			ExtraEnv: []string{"CGO_ENABLED=0"},
		},
		Test: TestConfig{
			Commands: []string{"go test ./..."},
			Skip:     false,
		},
		Deploy: DeployConfig{
			Port:       22,
			KeyPath:    "~/.ssh/id_rsa",
			RemotePath: "/opt/myapp/myapp",
			Service: ServiceConfig{
				Name:        "myapp",
				Description: "MyApp Service",
				Restart:     "on-failure",
			},
			HealthCheck: HealthCheckConfig{
				Timeout: 5,
			},
			PreDeploy:  []string{"sudo systemctl stop myapp"},
			PostDeploy: []string{"chmod +x /opt/myapp/myapp", "sudo systemctl start myapp"},
		},
	}

	var cancelled bool
	pages := tview.NewPages()

	// Track form field values via closures
	extraEnvStr := strings.Join(cfg.Build.ExtraEnv, ", ")
	testCmdsStr := strings.Join(cfg.Test.Commands, ", ")
	preDeployStr := strings.Join(cfg.Deploy.PreDeploy, ", ")
	postDeployStr := strings.Join(cfg.Deploy.PostDeploy, ", ")
	portStr := strconv.Itoa(cfg.Deploy.Port)
	timeoutStr := strconv.Itoa(cfg.Deploy.HealthCheck.Timeout)

	goosOptions := []string{"linux", "darwin", "windows"}
	goarchOptions := []string{"amd64", "arm64", "386", "arm"}
	restartOptions := []string{"on-failure", "always", "no"}

	goosIdx := indexOf(goosOptions, cfg.Build.GOOS)
	goarchIdx := indexOf(goarchOptions, cfg.Build.GOARCH)
	restartIdx := indexOf(restartOptions, cfg.Deploy.Service.Restart)

	pageNames := []string{"project", "build", "test", "deploy", "service", "hooks", "health", "review"}
	pageTitles := []string{
		"[1/8] Project",
		"[2/8] Build Settings",
		"[3/8] Test Settings",
		"[4/8] Deploy (SSH)",
		"[5/8] Systemd Service",
		"[6/8] Deploy Hooks",
		"[7/8] Health Check",
		"[8/8] Review & Generate",
	}
	currentPage := 0

	navigate := func(dir int) {
		currentPage += dir
		if currentPage < 0 {
			currentPage = 0
		}
		if currentPage >= len(pageNames) {
			currentPage = len(pageNames) - 1
		}
		pages.SwitchToPage(pageNames[currentPage])
	}

	makeNav := func(form *tview.Form, isFirst, isLast bool) {
		if !isFirst {
			form.AddButton("← Back", func() { navigate(-1) })
		}
		if !isLast {
			form.AddButton("Next →", func() { navigate(1) })
		}
		form.AddButton("Cancel", func() {
			cancelled = true
			app.Stop()
		})
	}

	// Helper to style forms
	styleForm := func(form *tview.Form, title string) *tview.Flex {
		form.SetBorder(true).
			SetTitle(" " + title + " ").
			SetTitleAlign(tview.AlignLeft).
			SetBorderColor(tcell.ColorDodgerBlue)
		form.SetFieldBackgroundColor(tcell.ColorDarkSlateGray)
		form.SetButtonBackgroundColor(tcell.ColorDodgerBlue)

		hint := tview.NewTextView().
			SetText("  Tab/Shift+Tab: navigate fields  •  Enter: activate  •  Esc: cancel").
			SetTextColor(tcell.ColorGray)

		flex := tview.NewFlex().SetDirection(tview.FlexRow).
			AddItem(form, 0, 1, true).
			AddItem(hint, 1, 0, false)
		return flex
	}

	// === Page 1: Project ===
	projectForm := tview.NewForm().
		AddInputField("Project Name", cfg.Project.Name, 40,
			nil,
			func(text string) { cfg.Project.Name = text }).
		AddTextView("Hint", "Your application name. Used for service naming and identification.", 60, 2, true, false)
	makeNav(projectForm, true, false)
	pages.AddPage("project", styleForm(projectForm, pageTitles[0]), true, true)

	// === Page 2: Build ===
	buildForm := tview.NewForm().
		AddInputField("Entry Point", cfg.Build.Entry, 40,
			nil,
			func(text string) { cfg.Build.Entry = text }).
		AddTextView("", "Go package path to build (e.g. \".\" or \"./cmd/server\")", 60, 1, true, false).
		AddInputField("Output Path", cfg.Build.Output, 40,
			nil,
			func(text string) { cfg.Build.Output = text }).
		AddTextView("", "Path for the compiled binary (e.g. \"bin/myapp\")", 60, 1, true, false).
		AddDropDown("Target OS (GOOS)", goosOptions, goosIdx,
			func(option string, index int) { cfg.Build.GOOS = option }).
		AddDropDown("Target Arch (GOARCH)", goarchOptions, goarchIdx,
			func(option string, index int) { cfg.Build.GOARCH = option }).
		AddInputField("Linker Flags", cfg.Build.LDFlags, 40,
			nil,
			func(text string) { cfg.Build.LDFlags = text }).
		AddTextView("", "\"-s -w\" strips debug info for smaller binaries", 60, 1, true, false).
		AddInputField("Extra Env Vars", extraEnvStr, 60,
			nil,
			func(text string) { extraEnvStr = text })
	buildForm.AddTextView("", "Comma-separated (e.g. \"CGO_ENABLED=0, GOFLAGS=-mod=vendor\")", 60, 1, true, false)
	makeNav(buildForm, false, false)
	pages.AddPage("build", styleForm(buildForm, pageTitles[1]), true, false)

	// === Page 3: Test ===
	testForm := tview.NewForm().
		AddInputField("Test Commands", testCmdsStr, 60,
			nil,
			func(text string) { testCmdsStr = text }).
		AddTextView("", "Comma-separated shell commands (e.g. \"go test ./..., go vet ./...\")", 60, 2, true, false).
		AddCheckbox("Skip Tests", cfg.Test.Skip,
			func(checked bool) { cfg.Test.Skip = checked }).
		AddTextView("", "If checked, tests will be skipped during deployment", 60, 1, true, false)
	makeNav(testForm, false, false)
	pages.AddPage("test", styleForm(testForm, pageTitles[2]), true, false)

	// === Page 4: Deploy ===
	deployForm := tview.NewForm().
		AddInputField("Host", cfg.Deploy.Host, 40,
			nil,
			func(text string) { cfg.Deploy.Host = text }).
		AddTextView("", "Server hostname or IP (e.g. \"deploy.example.com\")", 60, 1, true, false).
		AddInputField("Port", portStr, 10,
			tview.InputFieldInteger,
			func(text string) { portStr = text }).
		AddTextView("", "SSH port (default: 22)", 60, 1, true, false).
		AddInputField("User", cfg.Deploy.User, 30,
			nil,
			func(text string) { cfg.Deploy.User = text }).
		AddTextView("", "SSH username for the remote server", 60, 1, true, false).
		AddInputField("SSH Key Path", cfg.Deploy.KeyPath, 50,
			nil,
			func(text string) { cfg.Deploy.KeyPath = text }).
		AddTextView("", "Path to your SSH private key (supports ~/ expansion)", 60, 1, true, false).
		AddInputField("Remote Path", cfg.Deploy.RemotePath, 50,
			nil,
			func(text string) { cfg.Deploy.RemotePath = text }).
		AddTextView("", "Full path where the binary will be placed on the server", 60, 1, true, false)
	makeNav(deployForm, false, false)
	pages.AddPage("deploy", styleForm(deployForm, pageTitles[3]), true, false)

	// === Page 5: Service ===
	serviceForm := tview.NewForm().
		AddInputField("Service Name", cfg.Deploy.Service.Name, 30,
			nil,
			func(text string) { cfg.Deploy.Service.Name = text }).
		AddTextView("", "Systemd service unit name (e.g. \"myapp\")", 60, 1, true, false).
		AddInputField("Description", cfg.Deploy.Service.Description, 50,
			nil,
			func(text string) { cfg.Deploy.Service.Description = text }).
		AddTextView("", "Human-readable description for the systemd unit", 60, 1, true, false).
		AddDropDown("Restart Policy", restartOptions, restartIdx,
			func(option string, index int) { cfg.Deploy.Service.Restart = option }).
		AddTextView("", "on-failure: restart on crash  •  always: always restart  •  no: never restart", 60, 2, true, false)
	makeNav(serviceForm, false, false)
	pages.AddPage("service", styleForm(serviceForm, pageTitles[4]), true, false)

	// === Page 6: Hooks ===
	hooksForm := tview.NewForm().
		AddInputField("Pre-Deploy Commands", preDeployStr, 70,
			nil,
			func(text string) { preDeployStr = text }).
		AddTextView("", "Comma-separated commands to run BEFORE uploading the binary.\nExample: \"sudo systemctl stop myapp\"", 70, 2, true, false).
		AddInputField("Post-Deploy Commands", postDeployStr, 70,
			nil,
			func(text string) { postDeployStr = text }).
		AddTextView("", "Comma-separated commands to run AFTER uploading the binary.\nExample: \"chmod +x /opt/myapp/myapp, sudo systemctl start myapp\"", 70, 2, true, false)
	makeNav(hooksForm, false, false)
	pages.AddPage("hooks", styleForm(hooksForm, pageTitles[5]), true, false)

	// === Page 7: Health Check ===
	healthForm := tview.NewForm().
		AddInputField("Health Check URL", cfg.Deploy.HealthCheck.URL, 60,
			nil,
			func(text string) { cfg.Deploy.HealthCheck.URL = text }).
		AddTextView("", "HTTP endpoint to check after deploy (e.g. \"http://localhost:8080/health\")\nLeave empty to skip health checks.", 70, 2, true, false).
		AddInputField("Timeout (seconds)", timeoutStr, 10,
			tview.InputFieldInteger,
			func(text string) { timeoutStr = text })
	makeNav(healthForm, false, false)
	pages.AddPage("health", styleForm(healthForm, pageTitles[6]), true, false)

	// === Page 8: Review ===
	reviewText := tview.NewTextView().
		SetDynamicColors(true).
		SetText("[yellow]Press \"Generate\" to create deploy.yaml with your settings.\n\n[white]You can go back to any page to modify values.")
	reviewText.SetBorder(true).
		SetTitle(" [8/8] Review & Generate ").
		SetTitleAlign(tview.AlignLeft).
		SetBorderColor(tcell.ColorDodgerBlue)

	reviewForm := tview.NewForm()
	reviewForm.AddButton("← Back", func() { navigate(-1) })
	reviewForm.AddButton("Generate", func() {
		// Collect all string-parsed values
		cfg.Build.ExtraEnv = splitAndTrim(extraEnvStr)
		cfg.Test.Commands = splitAndTrim(testCmdsStr)
		cfg.Deploy.PreDeploy = splitAndTrim(preDeployStr)
		cfg.Deploy.PostDeploy = splitAndTrim(postDeployStr)
		if p, err := strconv.Atoi(portStr); err == nil {
			cfg.Deploy.Port = p
		}
		if t, err := strconv.Atoi(timeoutStr); err == nil {
			cfg.Deploy.HealthCheck.Timeout = t
		}
		app.Stop()
	})
	reviewForm.AddButton("Cancel", func() {
		cancelled = true
		app.Stop()
	})
	reviewForm.SetButtonBackgroundColor(tcell.ColorDodgerBlue)

	reviewFlex := tview.NewFlex().SetDirection(tview.FlexRow).
		AddItem(reviewText, 0, 1, false).
		AddItem(reviewForm, 3, 0, true)
	pages.AddPage("review", reviewFlex, true, false)

	// Global key handler for Esc
	app.SetInputCapture(func(event *tcell.EventKey) *tcell.EventKey {
		if event.Key() == tcell.KeyEscape {
			cancelled = true
			app.Stop()
			return nil
		}
		return event
	})

	// Title bar
	title := tview.NewTextView().
		SetTextAlign(tview.AlignCenter).
		SetText("🚀 Gondola — Deploy Configuration Wizard").
		SetTextColor(tcell.ColorDodgerBlue)

	layout := tview.NewFlex().SetDirection(tview.FlexRow).
		AddItem(title, 1, 0, false).
		AddItem(pages, 0, 1, true)

	if err := app.SetRoot(layout, true).EnableMouse(true).Run(); err != nil {
		panic(err)
	}

	if cancelled {
		return nil
	}

	return cfg
}

func splitAndTrim(s string) []string {
	if strings.TrimSpace(s) == "" {
		return nil
	}
	parts := strings.Split(s, ",")
	result := make([]string, 0, len(parts))
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" {
			result = append(result, p)
		}
	}
	return result
}

func indexOf(options []string, val string) int {
	for i, o := range options {
		if o == val {
			return i
		}
	}
	return 0
}

func init() {
	initCmd.Flags().BoolVar(&forceOverwrite, "force", false, "overwrite existing deploy.yaml")
	rootCmd.AddCommand(initCmd)
}
